import './balanceado/balanceado_datos.js'
import './balanceado/balanceado_datos_editar.js'
import './hp/hp_datos.js'
import './itkv/itkv_funciones.js'
import './mis/formulas_mis.js'
import './mis/traer_clases_mis.js'
import './mis/transferencia_mis.js'
import './ppr/control_claudio.js'
import './ppr/llamadas_claudio.js'
import './ppr/ppr_funciones.js'
import './ptc/enviar_datos.js'
import './ptc/envio_retenido_liberado.js'
import './ptc/ptc_claudio.js'
import './ptc/traer_clases.js'
import './recogida/funcionesRecogidas.js'
import './vimar/vimarDatos.js'
import './embarque.js'
import './embarque_funciones.js'
import './logistica.js'
import './logistica_funciones.js'
import './principal.js'

  
